id: I937CB9C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:03:38+00:00'
last_modified: '2022-06-09T14:19:18.448644+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2KG210298
  title: བཀའ་འགྱུར། ༼ཧེ་མིས་བྲིས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4BF3:
      image_group_id: I2KG211011
      title: ''
      total_pages: 321
      order: 1
      base_file: 4BF3.txt
    7C71:
      image_group_id: I2KG211012
      title: ''
      total_pages: 331
      order: 2
      base_file: 7C71.txt
    2FD1:
      image_group_id: I2KG211013
      title: ''
      total_pages: 323
      order: 3
      base_file: 2FD1.txt
    '5461':
      image_group_id: I2KG211014
      title: ''
      total_pages: 496
      order: 4
      base_file: 5461.txt
    305F:
      image_group_id: I2KG211015
      title: ''
      total_pages: 870
      order: 5
      base_file: 305F.txt
    4C62:
      image_group_id: I2KG211016
      title: ''
      total_pages: 776
      order: 6
      base_file: 4C62.txt
    1C31:
      image_group_id: I2KG211017
      title: ''
      total_pages: 971
      order: 7
      base_file: 1C31.txt
    01D2:
      image_group_id: I2KG211018
      title: ''
      total_pages: 470
      order: 8
      base_file: 01D2.txt
    338A:
      image_group_id: I2KG211019
      title: ''
      total_pages: 356
      order: 9
      base_file: 338A.txt
    CBE8:
      image_group_id: I2KG211021
      title: ''
      total_pages: 280
      order: 11
      base_file: CBE8.txt
    '2539':
      image_group_id: I2KG211022
      title: ''
      total_pages: 155
      order: 12
      base_file: 2539.txt
    '6246':
      image_group_id: I2KG211023
      title: ''
      total_pages: 434
      order: 13
      base_file: 6246.txt
    9B3D:
      image_group_id: I2KG211024
      title: ''
      total_pages: 586
      order: 14
      base_file: 9B3D.txt
    E75B:
      image_group_id: I2KG211027
      title: ''
      total_pages: 434
      order: 17
      base_file: E75B.txt
    '5055':
      image_group_id: I2KG211028
      title: ''
      total_pages: 544
      order: 18
      base_file: 5055.txt
    D786:
      image_group_id: I2KG211029
      title: ''
      total_pages: 473
      order: 19
      base_file: D786.txt
    '7797':
      image_group_id: I2KG211030
      title: ''
      total_pages: 472
      order: 20
      base_file: 7797.txt
    A336:
      image_group_id: I2KG211031
      title: ''
      total_pages: 451
      order: 21
      base_file: A336.txt
    40A5:
      image_group_id: I2KG211032
      title: ''
      total_pages: 454
      order: 22
      base_file: 40A5.txt
    DAAA:
      image_group_id: I2KG211033
      title: ''
      total_pages: 276
      order: 23
      base_file: DAAA.txt
    A69B:
      image_group_id: I2KG211035
      title: ''
      total_pages: 741
      order: 25
      base_file: A69B.txt
    921B:
      image_group_id: I2KG211036
      title: ''
      total_pages: 396
      order: 26
      base_file: 921B.txt
    F080:
      image_group_id: I2KG211038
      title: ''
      total_pages: 305
      order: 28
      base_file: F080.txt
    B0DB:
      image_group_id: I2KG211039
      title: ''
      total_pages: 373
      order: 29
      base_file: B0DB.txt
    '3303':
      image_group_id: I2KG211040
      title: ''
      total_pages: 573
      order: 30
      base_file: 3303.txt
    D227:
      image_group_id: I2KG211041
      title: ''
      total_pages: 372
      order: 31
      base_file: D227.txt
    '9021':
      image_group_id: I2KG211042
      title: ''
      total_pages: 351
      order: 32
      base_file: 9021.txt
    '7289':
      image_group_id: I2KG211043
      title: ''
      total_pages: 560
      order: 33
      base_file: 7289.txt
    '7414':
      image_group_id: I2KG211044
      title: ''
      total_pages: 767
      order: 34
      base_file: 7414.txt
    649E:
      image_group_id: I2KG211045
      title: ''
      total_pages: 595
      order: 35
      base_file: 649E.txt
    ED2E:
      image_group_id: I2KG211046
      title: ''
      total_pages: 798
      order: 36
      base_file: ED2E.txt
    4C59:
      image_group_id: I2KG211047
      title: ''
      total_pages: 619
      order: 37
      base_file: 4C59.txt
    AD6D:
      image_group_id: I2KG211048
      title: ''
      total_pages: 794
      order: 38
      base_file: AD6D.txt
    AFF9:
      image_group_id: I2KG211049
      title: ''
      total_pages: 577
      order: 39
      base_file: AFF9.txt
    BC0B:
      image_group_id: I2KG211050
      title: ''
      total_pages: 914
      order: 40
      base_file: BC0B.txt
    '4173':
      image_group_id: I2KG211051
      title: ''
      total_pages: 580
      order: 41
      base_file: 4173.txt
    99C9:
      image_group_id: I2KG211052
      title: ''
      total_pages: 467
      order: 42
      base_file: 99C9.txt
    26A3:
      image_group_id: I2KG211053
      title: ''
      total_pages: 466
      order: 43
      base_file: 26A3.txt
    '2359':
      image_group_id: I2KG211056
      title: ''
      total_pages: 244
      order: 46
      base_file: 2359.txt
    '4771':
      image_group_id: I2KG211057
      title: ''
      total_pages: 288
      order: 47
      base_file: 4771.txt
    387D:
      image_group_id: I2KG211058
      title: ''
      total_pages: 188
      order: 48
      base_file: 387D.txt
    '8883':
      image_group_id: I2KG211059
      title: ''
      total_pages: 360
      order: 49
      base_file: 8883.txt
    A28E:
      image_group_id: I2KG211060
      title: ''
      total_pages: 250
      order: 50
      base_file: A28E.txt
    F62D:
      image_group_id: I2KG211061
      title: ''
      total_pages: 122
      order: 51
      base_file: F62D.txt
    F86E:
      image_group_id: I2KG211063
      title: ''
      total_pages: 196
      order: 53
      base_file: F86E.txt
    12EE:
      image_group_id: I2KG211064
      title: ''
      total_pages: 291
      order: 54
      base_file: 12EE.txt
    CEEB:
      image_group_id: I2KG211066
      title: ''
      total_pages: 315
      order: 56
      base_file: CEEB.txt
    EF37:
      image_group_id: I2KG211067
      title: ''
      total_pages: 197
      order: 57
      base_file: EF37.txt
    9B29:
      image_group_id: I2KG211068
      title: ''
      total_pages: 317
      order: 58
      base_file: 9B29.txt
    FCCE:
      image_group_id: I2KG211069
      title: ''
      total_pages: 346
      order: 59
      base_file: FCCE.txt
    '8878':
      image_group_id: I2KG211070
      title: ''
      total_pages: 440
      order: 60
      base_file: 8878.txt
    61EE:
      image_group_id: I2KG211071
      title: ''
      total_pages: 66
      order: 61
      base_file: 61EE.txt
    14C6:
      image_group_id: I2KG211072
      title: ''
      total_pages: 100
      order: 62
      base_file: 14C6.txt
    0D2E:
      image_group_id: I2KG211073
      title: ''
      total_pages: 75
      order: 63
      base_file: 0D2E.txt
    554E:
      image_group_id: I2KG211074
      title: ''
      total_pages: 265
      order: 64
      base_file: 554E.txt
    29AD:
      image_group_id: I2KG211075
      title: ''
      total_pages: 424
      order: 65
      base_file: 29AD.txt
    5D44:
      image_group_id: I2KG211076
      title: ''
      total_pages: 285
      order: 66
      base_file: 5D44.txt
    FDC1:
      image_group_id: I2KG211077
      title: ''
      total_pages: 512
      order: 67
      base_file: FDC1.txt
    B69D:
      image_group_id: I2KG211078
      title: ''
      total_pages: 328
      order: 68
      base_file: B69D.txt
    C650:
      image_group_id: I2KG211079
      title: ''
      total_pages: 634
      order: 69
      base_file: C650.txt
    '0670':
      image_group_id: I2KG211080
      title: ''
      total_pages: 191
      order: 70
      base_file: 0670.txt
    44AE:
      image_group_id: I2KG211081
      title: ''
      total_pages: 338
      order: 71
      base_file: 44AE.txt
    6FE1:
      image_group_id: I2KG211082
      title: ''
      total_pages: 544
      order: 72
      base_file: 6FE1.txt
    945A:
      image_group_id: I2KG211083
      title: ''
      total_pages: 199
      order: 73
      base_file: 945A.txt
    C6F8:
      image_group_id: I2KG211084
      title: ''
      total_pages: 616
      order: 74
      base_file: C6F8.txt
    BCC0:
      image_group_id: I2KG211085
      title: ''
      total_pages: 642
      order: 75
      base_file: BCC0.txt
    4BE1:
      image_group_id: I2KG211086
      title: ''
      total_pages: 238
      order: 76
      base_file: 4BE1.txt
    CD48:
      image_group_id: I2KG211087
      title: ''
      total_pages: 180
      order: 77
      base_file: CD48.txt
    924F:
      image_group_id: I2KG211088
      title: ''
      total_pages: 289
      order: 78
      base_file: 924F.txt
    '5395':
      image_group_id: I2KG211089
      title: ''
      total_pages: 368
      order: 79
      base_file: 5395.txt
    4DCB:
      image_group_id: I2KG211090
      title: ''
      total_pages: 289
      order: 80
      base_file: 4DCB.txt
    7BD4:
      image_group_id: I2KG211091
      title: ''
      total_pages: 250
      order: 81
      base_file: 7BD4.txt
    9A80:
      image_group_id: I2KG211092
      title: ''
      total_pages: 476
      order: 82
      base_file: 9A80.txt
    9C5C:
      image_group_id: I2KG211093
      title: ''
      total_pages: 193
      order: 83
      base_file: 9C5C.txt
    77CC:
      image_group_id: I2KG211094
      title: ''
      total_pages: 241
      order: 84
      base_file: 77CC.txt
    8DE0:
      image_group_id: I2KG211095
      title: ''
      total_pages: 40
      order: 85
      base_file: 8DE0.txt
    BAC5:
      image_group_id: I2KG211096
      title: ''
      total_pages: 243
      order: 86
      base_file: BAC5.txt
    57FB:
      image_group_id: I2KG211097
      title: ''
      total_pages: 164
      order: 87
      base_file: 57FB.txt
    6CD8:
      image_group_id: I2KG211098
      title: ''
      total_pages: 303
      order: 88
      base_file: 6CD8.txt
    5BA6:
      image_group_id: I2KG211099
      title: ''
      total_pages: 352
      order: 89
      base_file: 5BA6.txt
    '1146':
      image_group_id: I2KG211100
      title: ''
      total_pages: 224
      order: 90
      base_file: 1146.txt
    C513:
      image_group_id: I2KG211101
      title: ''
      total_pages: 264
      order: 91
      base_file: C513.txt
    DCAC:
      image_group_id: I2KG211104
      title: ''
      total_pages: 338
      order: 94
      base_file: DCAC.txt
    E2E6:
      image_group_id: I2KG211109
      title: ''
      total_pages: 456
      order: 99
      base_file: E2E6.txt
    9EBE:
      image_group_id: I2KG211110
      title: ''
      total_pages: 424
      order: 100
      base_file: 9EBE.txt
    FC96:
      image_group_id: I2KG211112
      title: ''
      total_pages: 420
      order: 102
      base_file: FC96.txt
    F5AD:
      image_group_id: I2KG211114
      title: ''
      total_pages: 122
      order: 104
      base_file: F5AD.txt
    A7E8:
      image_group_id: I2KG211115
      title: ''
      total_pages: 321
      order: 105
      base_file: A7E8.txt
    440A:
      image_group_id: I2KG211116
      title: ''
      total_pages: 24
      order: 106
      base_file: 440A.txt
    86FA:
      image_group_id: I2KG211117
      title: ''
      total_pages: 168
      order: 107
      base_file: 86FA.txt
    '7739':
      image_group_id: I2KG211118
      title: ''
      total_pages: 975
      order: 108
      base_file: 7739.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
